#!/bin/sh

die()
{
	echo "$1" >&2
	exit 1
}

dbg()
{
	echo "DBG $1" >&2
}

if [ $# -ne 2 ]; then
	die "Usage: debian-build-repo <pkgs_dir> <repo_dir>"
fi

if [ -z "$KEY_ID" ] && [ -z "$SKIP_SIGN" ]; then
	die "Environment variable KEY_ID is unset; must be set to the ID of the signing key."
fi

get_tempdir()
{
	mktemp --tmpdir -d debian-repo-build.XXXXXX
}

cleanup_workspace()
{
	[ -z "$WORK_DIR" ] && rm -rf "$TMPDIR"
	exit 0
}

init_workspace()
{
	if [ -z "$WORK_DIR" ]; then
		TMPDIR="$(get_tempdir)"
	else
		TMPDIR="$WORK_DIR"
	fi
}

get_workdir()
{
	local name="$1"
	[ -z "$TMPDIR" ] && die "Workspace has not been initialized, can't get a workdir."
	echo "$TMPDIR/$name"
}

on_exit()
{
	cleanup_workspace
}

trap on_exit EXIT

PKGDIR="$1"
REPODIR="$2"

find_dist_debs()
{
	local pkgdir="$1"
	local dist_name="$2"

	(cd "$pkgdir"; du -a "$dist_name" --exclude '.*' | awk '{print $2}' | grep '\.deb$')
}

get_compress_opt()
{
	local filename="$1"
	case "$filename" in
	  *.gz)
		echo "-z"
	  ;;
 	  *.bz2)
	        echo "-j"
	  ;;
	  *.xz)
	        echo "-J"
	  ;;
	  *.lzma)
	        echo "--lzma"
	  ;;
	  *.tar)
	        echo ""
	  ;;
	  *)
		die "Urecognized file extension for archive $pkgfile"
	esac
}

extract_control()
{
	local pkgfile="$1"
	local control_file="$(ar t "$pkgfile" | grep '^control\.' | sed 1q)" || die "Unable to locate control archive for package $pkgfile"
	local compress_opt="$(get_compress_opt "$control_file")" || die "Unable to determine decompression option for $pkgfile"
	ar p "$pkgfile" "$control_file" | tar -O $compress_opt -xf - ./control || die "Failure extracting control file from package $pkgfile"
}

extract_filelist()
{
	local pkgfile="$1"
	local data_file="$(ar t "$pkgfile" | grep '^data\.' | sed 1q)" || die "Unable to locate data archive for package $pkgfile"
	local compress_opt="$(get_compress_opt "$data_file")" || die "Unable to determine compression option for $pkgfile"
	ar p "$pkgfile" "$data_file" | tar $compress_opt -tf - | grep -v '/$' | sed -e 's|^./||' || die "Failure to extract file list from package $pkgfile"
}

trim_word()
{
	echo "$1" | (read word; echo $word)
}

control_arch()
{
	local file="$1"
	test -f "$file" || die "Control file $file does not exist."
	local arch="$(trim_word "$(grep '^Architecture: ' "$file" | sed -e 's/^Architecture: \(.*\)/\1/')")"
	if [ $? -ne 0 ] || [ -z "$arch" ]; then
		die "Unable to determine package architecture"
	fi
	echo $arch
}

control_section()
{
	local file="$1"
	test -f "$file" || die "Control file $file does not exist."
	trim_word "$(grep '^Section: ' "$file" | sed -e 's/^Section: \(.*\)/\1/')" || true
}

control_pkgname()
{
	local file="$1"
	test -f "$file" || die "Control file $file does not exist."
	local name="$(trim_word "$(grep '^Package: ' "$file" | sed -e 's/^Package: \(.*\)/\1/')")"
	if [ $? -ne 0 ] || [ -z "$name" ]; then
		die "Unable to determine package name"
	fi
	echo $name
}

control_description()
{
	local file="$1"
	awk '
BEGIN { do_print=0; }
/^[^ ]/ { if (do_print) do_print = 0; }
/^Description: / { do_print = 1; }
{ if (do_print) print $0; }
' "$file" | sed -e 's/^Description: //'
	
}

extract_package_info()
{
	local pool_path="$1"
	# pool-relative path to the package.
	local pkg_pool_path="$2"
	local pkg_meta_dir="$3"

	local debfile="$pool_path/$pkg_pool_path"

	rm -rf "$pkg_meta_dir"
	mkdir -p "$pkg_meta_dir"

	local component_count="$(echo "$pkg_pool_path" | awk -F '/' 'BEGIN {count=0;} {count = count + NF - 1;} END {print count;}')"
	if [ "$component_count" -lt 2 ]; then
		die "Package path '$pkg_pool_path' does not have at least a dist and component parent directory -- is this an archive-style package directory?"
	fi
	local dist_name="$(echo "$pkg_pool_path" | cut -f 1 -d '/')"
	local component_name="$(echo "$pkg_pool_path" | cut -f 2 -d '/')"
	echo "$component_name" > "$pkg_meta_dir/component"

	local control_file="$(ar t "$debfile" | sed -n '2p')"
	local data_file="$(ar t "$debfile" | sed -n '3p')"

	local control_decompress_opt="$(get_compress_opt "$control_file")"
	local data_decompress_opt="$(get_compress_opt "$data_file")"

	extract_control "$debfile" > "$pkg_meta_dir/control" || die "Unable to extract package control file"
	extract_filelist "$debfile" > "$pkg_meta_dir/filelist" || die "Unable to extract package file list"

	local arch="$(control_arch "$pkg_meta_dir/control")" || die "Unabled to extract package architecture"
	echo "$arch" > "$pkg_meta_dir/architecture"

	local name="$(control_pkgname "$pkg_meta_dir/control")" || die "Unable to extract package name"
	echo "$name" > "$pkg_meta_dir/name"

	local section="$(control_section "$pkg_meta_dir/control")" || die "Unable to extract package section"
	if ! [ -z "$section" ]; then
		echo "$section" > "$pkg_meta_dir/section"
	fi

	# Link the package file.
	ln -s "$debfile" "$pkg_meta_dir/package.deb"

	# Record the package's pool-relative path
	echo "$pkg_pool_path" > "$pkg_meta_dir/path"
}

build_packages_entry()
{
	# pkg-dir-relative package file name
	local pkg_metadir="$1"

	local control_file="$pkg_metadir/control"

	# Packages paragraphs must begin with the Package: field, so make sure that happens.
	local package_field_count="$(grep '^Package: ' "$control_file" | wc -l)"
	if [ "$package_field_count" -gt 1 ]; then
		die "Package has multiple Package: entries, control file is invalid."
	fi

	local package_field="$(grep '^Package: ' "$control_file" | sed 1q)" || die "Package control file does not include a Package field, it is invalid."
	echo "$package_field"

	local description="$(control_description "$control_file")" || die "Unable to extract package control description"
	local md5sum_checksum="$(echo "$description" | md5sum | awk '{print $1}')" || die "Error checksumming package description"
	# Note that we avoid stripping possibly invalid duplicate Package:
	# fields by bailing out if there is more than one of them above.
	cat "$control_file" | grep -v '^Package: ' || die "Error copying package control paragraph to Packages index"
	echo "Description-md5sum: $md5sum_checksum"
	echo "Filename: pool/$(cat "$pkg_metadir/path")" || die "Unable to write pool-relative package path (!)"
	echo "Size: $(du -b "$(readlink "$pkg_metadir/package.deb")" | cut -f 1)"
	echo "SHA256: $(sha256sum $(readlink "$pkg_metadir/package.deb") | awk '{print $1}')" || die "Unable to compute package checksum"
	echo "SHA512: $(sha512sum $(readlink "$pkg_metadir/package.deb") | awk '{print $1}')" || die "Unable to compute package checksum"
}

lines_list()
{
	local separator="$1"
	local list=""
	while IFS="" read -r item; do
		if ! [ -z "$list" ]; then
			list="${list}${separator}"
		fi
		list="${list}${item}"
	done
	echo $list
}

file_hash_info()
{
	local algo="$1"
	local base_dir="$2"
	local path="$3"

	local hash_cmd="${algo}sum"

	# <hash> <byte size> <path> (du provides both path and size -- be careful about the paths used)
	(cd "$base_dir"; echo "$("$hash_cmd" "$path" | awk '{print $1}') $(du -b $path)")
}

set_dist_arch()
{
	local dist_dir="$1"
	local arch_name="$2"

	mkdir -p "$dist_dir/architectures"
	touch "$dist_dir/architectures/$arch_name"
}

get_dist_architectures()
{
	local dist_dir="$1"
	ls "$dist_dir/architectures"
}

set_dist_component()
{
	local dist_dir="$1"
	local component_name="$2"

	mkdir -p "$dist_dir/components"
	touch "$dist_dir/components/$component_name"
}

get_dist_components()
{
	local dist_dir="$1"
	ls "$dist_dir/components"
}

dist_index_files()
{
	local dist_dir="$1"

	get_dist_components "$dist_dir" | (
		while IFS="" read -r component; do
			get_dist_architectures "$dist_dir" | (
				while IFS="" read -r arch; do
					# We have a Packages index in <component>/binary-<arch>/, and also a Contents-<arg>.gz index under <component>/
					(cd "$dist_dir"; \
						ls -d "$component/binary-$arch/"*; \
						ls -d "$component/Contents-"*.gz)
				done
			)
		done
	)
}

build_release()
{
	local meta="$1"
	local dist_name="$2"

	echo "Architectures: $(get_dist_architectures "$meta" | lines_list " ")"
	echo "Components: $(get_dist_components "$meta" | lines_list " ")"
	echo "Suite: $dist_name"
	echo "Date: $(date -R -u)"
	echo "NotAutomatic: yes"
	echo "ButAutomaticUpgrades: yes"
	echo "SHA256:"
	dist_index_files "$meta" | (
		while IFS="" read -r index; do
			echo "  $(file_hash_info sha256 "$meta" "$index")" || die "Unable to checksum index file $index in $meta"
		done
	)
	echo "SHA512:"
	dist_index_files "$meta" | (
		while IFS="" read -r index; do
			echo "  $(file_hash_info sha512 "$meta" "$index")" || die "Unable to checksum index file $index in $meta"
		done
	)
}

build_dist_meta()
{
	local meta="$1"
	local dist_name="$2"

	echo "Building release index" >&2
	build_release "$meta" "$dist_name" > "$meta/Release" || die "Failed to build Release file"

	if ! [ -z "$SKIP_SIGN" ]; then
		exit 0
	fi
	echo "Creating clearsigned InRelease index" >&2
	gpg -a -s --clearsign --local-user "$KEY_ID" --output "$meta/InRelease" "$meta/Release" || die "Failed to create signed InRelease file"
	echo "Creating detached Release index signature" >&2
	gpg -a -b -s --local-user "$KEY_ID" --output "$meta/Release.gpg" "$meta/Release" || die "Failed to create detached signature file for Release index"
}

copy_meta_to_repo()
{
	local meta="$1"
	local repo_dir="$2"

	ls "$meta" | (
		while IFS="" read -r dist; do
			dist_meta="$meta/$dist"
			target="$repo_dir/dists/$dist"
			mkdir -p "$target"
			cp "$dist_meta/Release" "$target" || die "Failed to copy release index files"
			if [ -z "$SKIP_SIGN" ]; then
				cp "$dist_meta/InRelease" "$dist_meta/Release.gpg" "$target" || die "Failed to copy release index files"
			fi

			echo "$(get_dist_components "$dist_meta")" | (
				while IFS="" read -r component; do
					cp -r "$dist_meta/$component" "$target"
				done
			)
		done
	)
}

build_contents_entries()
{
	local pkg_meta_dir="$1"

	local section_prefix=""
	if [ -f "$pkg_meta_dir/section" ]; then
		section_prefix="$(cat "$pkg_meta_dir/section")/"
	fi

	local pkg_name="$(cat "$pkg_meta_dir/name")" || die "Unable to read package name from extracted information"
	while IFS="" read -r path; do
		printf '%-60s %s\n' "$path" "$section_prefix$pkg_name"
	done <"$pkg_meta_dir/filelist" || die "Error writing package contents"
}

add_packages_to_dist()
{
	local pkg_dir="$1"
	local dist_meta_dir="$2"

	local pkg_meta_dir="$(get_workdir pkg)"
	while IFS="" read -r pkg; do
		echo "Updating repo with package $pkg..." >&2
		rm -rf "$pkg_meta_dir"
		mkdir -p "$pkg_meta_dir"
		extract_package_info "$pkg_dir" "$pkg" "$pkg_meta_dir" || die "Unable to extract package information for package $pkg"

		# Update the set of architectures.
		local arch="$(cat "$pkg_meta_dir/architecture")" || die "Package meta is missing package architecture"
		set_dist_arch "$dist_meta_dir" "$arch" || die "Unable to record package architecture in dist meta"

		# Update the set of components.
		local component="$(cat "$pkg_meta_dir/component")" || die "Package meta is missing package component"
		set_dist_component "$dist_meta_dir" "$component" || die "Unable to record package component in dist meta"

		# Create the arch directory for this component.
		mkdir -p "$dist_meta_dir/$component/binary-$arch"
		local pkg_index="$dist_meta_dir/$component/binary-$arch/Packages"

		if [ -s "$pkg_index" ]; then
			echo "" >> "$pkg_index"
		fi
		build_packages_entry "$pkg_meta_dir" >> "$pkg_index"

		local contents_index="$dist_meta_dir/$component/Contents-$arch"
		build_contents_entries "$pkg_meta_dir" >> "$contents_index"
	done
}

build_dist()
{
	local pkg_dir="$1"
	local dist_name="$2"
	local meta_dir="$3"

	local dist_meta="$meta_dir/$dist_name"
	mkdir "$dist_meta"
	find_dist_debs "$pkg_dir" "$dist_name" > "$dist_meta/pkglist" || die "Error locating package files"
	add_packages_to_dist "$pkg_dir" "$dist_meta" < "$dist_meta/pkglist" || die "Error adding packages to dist $dist_name"

	# The Contents index(es) must be gzipped.
	echo "$(get_dist_components "$dist_meta")" | (
		while  IFS="" read -r component; do
			ls "$dist_meta/$component"/Contents-* | xargs -n 1 gzip
		done
	)

	build_dist_meta "$dist_meta" "$dist_name" || die "Failure building Release information for dist $dist_name"
}

make_absolute_path()
{
	local path="$1"

	if echo "$path" | grep -q '^/'; then
		echo "$path"
	else
		echo "$PWD/$path"
	fi
}

build_repo()
{
	local pkg_dir="$1"
	local repo_dir="$2"

	local meta_dir="$(get_workdir meta)"

	mkdir -p "$meta_dir"
	(cd "$meta_dir"; ls -A | xargs -n 1 rm -rf) || die "Error clearing output directory contents"

	ls "$pkg_dir" | (
		while IFS="" read -r dist; do
			echo "Building dist $dist" >&2
			build_dist "$pkg_dir" "$dist" "$meta_dir" || die "Failure building dist $dist"
		done
	)

	rm -rf "$repo_dir"
	mkdir -p "$repo_dir"
	local pkg_path="$(make_absolute_path "$pkg_dir")"
	# Link in the package pool
	ln -s "$pkg_path" "$repo_dir/pool"
	copy_meta_to_repo "$meta_dir" "$repo_dir" || die "Failed to copy repository information to repository"

	if [ -z "$SKIP_SIGN" ]; then
		echo "Exporting signing key" >&2
		gpg -a --export --output "$repo_dir/Key.gpg" "$KEY_ID" || die "Failed to export public signing key"
	fi
}

init_workspace || die "Failed to set up workspace"
build_repo "$PKGDIR" "$REPODIR" || die "Failure building repo at $REPODIR"
